sudo: true
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - docker build -t goserver .
    - docker images
    - docker tag goserver $DOCKER_USER/goserver
    - docker push $DOCKER_USER/goserver
env:
  global:
  - secure: Z+C9zBj3RAvCTUqATNmj0LtKTmIsp3zL2VrMmUQEDNvQTx9xFhCHPCi1EPddq8jmCeVlw0hJAMuJG4oq+BIKvG0UvIIM7LZjefr3FPMDBqnj2J7GWWa7oGx7brxaSMEjKH1qjnqznto7spJGbEmu9PkfSxa585oVgu0EDOmGjzIDpWbsKbbtywAvwpWBA7a4dgdARD8agcigHd9SeBByUPd9hnFpx0ODtCQ28Eqb+pa39agpc5XklZSX1X2aF25Q+NeTya9LibbkkBFm7bKcxmTc+nLcaFmYZMpy9VmWJ+zEN1trLIms0VKt9mpGi2O5xT4JEFjZsuW2wKS+brkmNb4qnP8eATqSvgDzxKbw4PvavZ3RPKO0bBf+ho9LanJVydFW++ZoV8BuHtJ3n+gdwJiBbVHA3O/fsA6Jhj2xPdHN/cOmzwwlSld7U8JSF3kzgFZ8wNB6cQUbJJIcY/cOxuGRQMqjIHngoIPglY3zszAyKQ0bkanbjDYTGPrgWbb7nOw6wwy0TBptzN5u21yez9YZMcHduiuarMhf6WD09msX80Cd25mShdATe3v1hUOAadJM6o3cyg59dKKazXBZQ7s0efLlv1oV5TOuf3AqRB/Cw/gu6SDEtQ1VpOVuEJyApuLQ9WN8B9EoWhc7w+EVpoITp1nK81XRNKm9kKcicqU=
  - secure: XBIOTXQ6k+vBJtqFarikSerfD1Yl6Xj8uaKYL3E4J43l4bp4nR6z3Tkn5oLXV7S/URf3q9ZQvDb+TllYgb4uUi+5axUPbzZDURzuw0VcdxjU6y/kZY23c2pLBNUflkjIQpSq0KLkq2zA6KGxxb5BHSLS7bbS6m1vYZ2ox6X5ORFDQtaUfSeWe/8txDdTBKcc8lJ1TKsQZv7IwAAwxiBhiNaKU+FTEhaAA8wJ2xfVH1yNLtegl/ip+ku2+OPUM02eB3eCKs4hQOX3wQJsjvorisVXlSoP9ZNTG9I7q9IfrMUQpl8LxVZnJL61xbUQDIFLKCsIRaS5KvEIbhcuxwjXJGCEf5motoeTCTK5Ms26uJfUJKsDOKP/IFnxzCCBH+n7JSebYHRwr3h/rJAkJOAKn4YHiXY75D54Bk1+850cWuWMpENOYUZP8f7fqh24mk8mIEFZVHfmHext4AZjyYJ9N1qThNxFN/Y895Bp4xUkDe/Nqryc5DKhoWx4chTveIIhSUJ++wi5uGy8RzoDiSkACQ95vNGnntJu6/7jarw0tOrpn4MOF9BraYWdswYMh2BwdL0w3oGKINjMluYhVFZZO3KhcuCN+iQU8BFrih26mWSE0m2AcOmom0Sh7hiFCrKDqHB2faiNsv5CLw6e2VCpcw21mIUSTST6h8HQrh6Puhg=
