sudo: true
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - docker build -t goserver .
    - docker images
    - docker tag goserver $DOCKER_USER/goserver
    - docker push $DOCKER_USER/goserver
