apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: golangdemoa
  labels:
    app: golang-demo-a
spec:
  type: NodePort
  ports:
  - port: 8080
    name: golangdemoa
  selector:
    app: golang_demo_a
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golangdemoa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-demo-a
    spec:
      containers:
      - name: golang-demo-a-c
        image: khv129/golang_demo_a
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

